apiVersion: v1
kind: Service
metadata:
  name: configurable-agent
  labels:
    app.kubernetes.io/name: configurable-agent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: configurable-agent
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
