apiVersion: v1
kind: Service
metadata:
  name: wally
  labels:
    app.kubernetes.io/name: wally
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wally
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
