#!/usr/bin/env node
// Harvest fixture recorder — turn an agent SSE dump into a mock fixture.
//
// Reads the agent's event stream (the `event: tool_call` / `event: tool_result`
// lines you see in the agent output), extracts the Harvest data returned by
// `list_users` / `list_projects` / `list_time_entries`, de-duplicates by id, and
// writes a fixture compatible with examples/harvest/harvest-mock.mjs.
//
//   node examples/harvest/harvest-record.mjs run.sse > examples/harvest/scenario.json
//   pbpaste | node examples/harvest/harvest-record.mjs > examples/harvest/scenario.json
//
// If list_users returned no users (as happens on accounts where the token can't
// list members), users are derived from the user_id/user_name found on the
// recorded time entries, so the output is immediately usable by the mock.

import { readFileSync } from 'node:fs';

const HARVEST_TOOLS = new Set(['list_users', 'list_projects', 'list_time_entries']);

function readInput() {
  const file = process.argv[2];
  if (file && file !== '-') {
    return readFileSync(file, 'utf8');
  }
  return readFileSync(0, 'utf8'); // stdin
}

// Pull the JSON payload out of every `data: { ... }` SSE line. Each event is a
// single line in the dumps the agent produces.
function parseSseDataLines(text) {
  const payloads = [];
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (!line.startsWith('data:')) continue;
    const json = line.slice('data:'.length).trim();
    if (!json || json === '[DONE]') continue;
    try {
      payloads.push(JSON.parse(json));
    } catch {
      // Non-JSON data line (e.g. a token delta) — ignore.
    }
  }
  return payloads;
}

// A tool_result payload looks like:
//   { id, output: { label, status, content: "<json string>", args, ... } }
// `content` is itself a JSON string holding { users | projects | time_entries }.
function extractToolResults(payloads) {
  const results = [];
  for (const p of payloads) {
    const out = p?.output;
    if (!out || !HARVEST_TOOLS.has(out.label)) continue;
    if (out.status && out.status !== 'succeeded') continue;
    let parsed;
    try {
      parsed = typeof out.content === 'string' ? JSON.parse(out.content) : out.content;
    } catch {
      continue;
    }
    results.push({ tool: out.label, data: parsed });
  }
  return results;
}

function mergeById(target, items, idKey = 'id') {
  for (const item of items ?? []) {
    if (item && item[idKey] != null && !target.has(item[idKey])) {
      target.set(item[idKey], item);
    }
  }
}

function main() {
  const payloads = parseSseDataLines(readInput());
  const results = extractToolResults(payloads);

  if (results.length === 0) {
    console.error(
      '[harvest-record] no Harvest tool results found in input. Expected `data:` lines with output.label in {list_users, list_projects, list_time_entries}.',
    );
    process.exit(1);
  }

  const users = new Map();
  const projects = new Map();
  const timeEntries = new Map();

  for (const { tool, data } of results) {
    if (tool === 'list_users') mergeById(users, data.users);
    if (tool === 'list_projects') mergeById(projects, data.projects);
    if (tool === 'list_time_entries') mergeById(timeEntries, data.time_entries);
  }

  let derivedUsers = false;
  if (users.size === 0 && timeEntries.size > 0) {
    derivedUsers = true;
    for (const e of timeEntries.values()) {
      if (e.user_id != null && !users.has(e.user_id)) {
        const [first, ...rest] = String(e.user_name ?? '').split(' ');
        users.set(e.user_id, {
          id: e.user_id,
          first_name: first ?? '',
          last_name: rest.join(' '),
          name: e.user_name ?? '',
          is_active: true,
        });
      }
    }
  }

  const fixture = {
    _comment: `Generated by examples/harvest/harvest-record.mjs from an agent SSE dump.${
      derivedUsers ? ' users were derived from time_entries (list_users returned none).' : ''
    }`,
    users: [...users.values()],
    projects: [...projects.values()],
    time_entries: [...timeEntries.values()],
  };

  process.stdout.write(`${JSON.stringify(fixture, null, 2)}\n`);
  console.error(
    `[harvest-record] wrote ${fixture.users.length} users, ${fixture.projects.length} projects, ${fixture.time_entries.length} time entries` +
      `${derivedUsers ? ' (users derived from time entries)' : ''}`,
  );
}

main();
